name: CI

on:
  push:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Zig
        # Version is pulled from build.zig.zon
        uses: mlugg/setup-zig@v2
        with:
          use-cache: false

      - name: Build project
        env:
          ZIG_GLOBAL_CACHE_DIR: /home/runner/.cache/zig
          ZIG_LOCAL_CACHE_DIR: .zig-cache
        run: zig build

      - name: Run tests
        env:
          ZIG_GLOBAL_CACHE_DIR: /home/runner/.cache/zig
          ZIG_LOCAL_CACHE_DIR: .zig-cache
        run: zig build test --summary all
